/** GLB配置パス（public/models/ 配下） */
export const CUSTOM_BAG_MODEL_URL = '/models/custom-bag.glb'

/** GLB内メッシュ名（scripts/generate-bag-glb.mjs と一致させる） */
export const MESH_NAMES = [
  'body',
  'side',
  'bottom',
  'handle',
  'handle2',
  'ring-single',
  'ring-dual',
  'clasp',
  'clasp-shield',
  'flap',
  'pocket',
  'pocket-back',
  'pocket-l',
  'pocket-r',
  'plate',
  'chain',
  'charm',
  'charm-star',
  'charm-heart',
  'charm-tassel',
  'charm-tag',
  'strap-chain',
  'drum-body',
  'drum-side',
  'drum-zip-tape',
  'drum-zip-teeth',
  'belt',
  'belt-stitch',
  'tab-0',
  'tab-1',
  'tab-2',
  'tab-3',
  'tab-ring-0',
  'tab-ring-1',
  'tab-ring-2',
  'tab-ring-3',
  'side-rings',
  'flap-round',
  'flap-curve',
  'flap-point',
  'stud-0',
  'stud-1',
  'stud-2',
  'stud-3',
  'zip-tape',
  'zip-teeth',
  'zip-tape-top',
  'zip-teeth-top',
  'opening-mouth',
  'frame',
  'magnet-tab',
  'magnet-snap',
  'puller-slider',
  'puller-ring',
  'puller-tab',
  'puller-tassel',
  'puller-bar',
  'puller2-slider',
  'puller2-ring',
  'puller2-tab',
  'puller2-tassel',
  'puller2-bar',
] as const

export type MeshName = (typeof MESH_NAMES)[number]

export function isMeshName(name: string): name is MeshName {
  return (MESH_NAMES as readonly string[]).includes(name)
}
